version: "3.9"
services:
  diplicity-application:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: diplicity-application
    entrypoint:
      [
        "python3",
        "../../../usr/local/gcloud/google-cloud-sdk/bin/dev_appserver.py",
        "--host=0.0.0.0",
        "--admin_host=0.0.0.0",
        "--enable_host_checking=False",
        ".",
      ]
    volumes:
      - .:/go/src/app
    networks:
      - diplicity-net
    ports:
      - "8080:8080"
      - "8000:8000"
  diplicity-configurator:
    image: curlimages/curl:latest
    container_name: diplicity-configurator
    depends_on:
      - diplicity-application
    entrypoint: >
      sh -c "
      sleep 20 &&
      curl -XPOST http://diplicity-application:8080/_configure
      -d '{\"OAuth\": { \"ClientID\": \"${OAUTH_CLIENT_ID}\", \"Secret\": \"${OAUTH_SECRET}\" }}'
      "
    env_file:
      - .env
    networks:
      - diplicity-net
networks:
  diplicity-net:
    name: diplicity-net
    driver: bridge
