runtime: go
api_version: go1

inbound_services:
- mail

handlers:
- url: /(firebase-messaging-sw.js)
  static_files: js/\1
  upload: js/firebase-messaging-sw.js
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /.*
  script: _go_app
  secure: always
