name: Test diplicity

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test server
        run: docker compose up -d diplicity-test-application

      - name: Run tests
        run: docker-compose up --exit-code-from diplicity-tests diplicity-tests
