name: Test diplicity

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.20'
                  check-latest: true
            - name: Check Go version
              run: go version
            - name: Set up Python 2.7
              run: sudo apt install python2.7
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
            - name: Debug log GoogleCloudPlatform info
              run: gcloud info
            - name: Install App Engine Go
              run: gcloud components install app-engine-go
            - name: Extract GoogleCloudPlatform installation root
              run: echo "GCLOUD_ROOT=$(gcloud info | grep 'Installation Root:' | sed -e 's/.*\[\([^]]\+\).*/\1/')" >> $GITHUB_ENV
            - name: Check out code
              uses: actions/checkout@v2
            - name: Start test server
              run: ${GITHUB_WORKSPACE}/diptest/start_test_server.sh
            - name: Run tests
              run: cd diptest && go test -v -timeout 40m
